### ISSUE TITLE
how does this compare to buffer-to-uint8array?

### ISSUE THREAD

**Issue by mmckegg** [ahdinosaur/buffer-to-typed-array#1]
https://github.com/substack/buffer-to-uint8array

**Comment by ahdinosaur** [comment]
it's generalized for any `TypedArray`, not only `Uint8Array`. it also supports conversions from multi-byte types where endian-ness is relevant. i made it for [read-audio v3](https://github.com/livejs/read-audio/tree/v3) as SoX supports raw audio output in many formats so this made my code cleaner.

**Comment by mmckegg** [comment]
``` js
new Float32Array(bufferToUint8Array(buffer).buffer)
```

But fair enough, nice to have something purpose built.

**Comment by ahdinosaur** [comment]
ah cool, good to know. in that case, perhaps the only reason to use this is if you have buffers coming in with a particular endian different from your normal endian, as typed arrays don't give you control over that. my laptop is a different endian than my beaglebone, so this way i can ensure the endian from SoX (which is configurable but i'd rather not have to worry about endian compatibility) is converted into whatever endian is on the computer.

**Comment by ahdinosaur** [comment]
as a note: [in 2.0.0](https://github.com/livejs/buffer-to-typed-array/commit/ad84ca2b349c854e08a754bdc163182b7cf23f9d), i pushed @mmckegg's simple implementation to `./index.js` in  and moved my (broken) endian buffer code to `./endian.js`.
