### ISSUE TITLE
Is a buffer's .byteOffset respected?

### ISSUE THREAD

**Issue by mk-pmb** [ahdinosaur/buffer-to-typed-array#5]
I found the node buffer docs' [`buf.byteOffset` chapter](https://nodejs.org/api/buffer.html#buffer_buf_byteoffset) says we need to take that offset into account. Trying to add a test case, I wasn't able to trigger it, but I wonder, could it be a problem?
Is that the reason why you `require('buffer-to-uint8array')`? In that case we should add a comment to explain. Currently I can't see any benefit in using that external lib at all.

**Comment by ahdinosaur** [comment]
sure, happy to merge a pull request constructing a typed array directly, then publish as a major version (in case this changes any behaviors)! :heart:
